import type { Metadata } from "next";
import Container from "@/components/Container";
import Breadcrumbs from "@/components/Breadcrumbs";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: "Privacy policy for Canada EU Entry / OneTitel, describing how personal data is processed.",
  alternates: { canonical: "/privacy-policy" },
};

export default function PrivacyPolicyPage() {
  return (
    <section className="py-16 md:py-24">
      <Container className="max-w-2xl">
        <Breadcrumbs items={[{ href: "/", label: "Home" }, { href: "/privacy-policy", label: "Privacy Policy" }]} />
        <h1 className="mt-6 font-serif text-3xl font-semibold text-navy">Privacy Policy</h1>
        <p className="mt-2 text-sm font-medium uppercase tracking-wider text-accent">
          Draft — requires review by a qualified German/EU data-protection professional before
          publication
        </p>

        <div className="prose-onetitel mt-8">
          <h2>1. Controller</h2>
          <p>
            [Placeholder: full legal name and address of the data controller, matching the Legal
            Notice.] Contact for data-protection matters: [placeholder email].
          </p>

          <h2>2. What data we process</h2>
          <ul>
            <li>Contact-form submissions (name, company, email, message content)</li>
            <li>Basic website analytics, where and if enabled with appropriate consent</li>
            <li>Technical log data generated by normal website operation</li>
          </ul>

          <h2>3. Purpose and legal basis</h2>
          <p>
            [Placeholder: describe purposes — responding to inquiries, operating the website —
            and the applicable GDPR legal basis for each, e.g., Article 6(1)(b) or 6(1)(f), to be
            confirmed by a qualified professional.]
          </p>

          <h2>4. Cookies and consent</h2>
          <p>
            This website does not enable non-essential tracking, analytics or marketing cookies
            before consent is obtained through a consent-management mechanism. [Placeholder:
            describe the specific consent tool once implemented, and list any cookies or
            third-party services actually in use.]
          </p>

          <h2>5. Data sharing</h2>
          <p>
            [Placeholder: list any processors — e.g., email or hosting providers — and their role,
            once finalized.]
          </p>

          <h2>6. International transfers</h2>
          <p>
            [Placeholder: describe any transfer of personal data outside the EU/EEA, including to
            Canada, and the safeguard relied upon, e.g., an adequacy decision or standard
            contractual clauses, to be confirmed by a qualified professional.]
          </p>

          <h2>7. Retention</h2>
          <p>[Placeholder: retention periods for inquiry and contact data.]</p>

          <h2>8. Your rights</h2>
          <p>
            Under the GDPR, you have the right to access, rectify, erase, restrict or object to
            the processing of your personal data, and the right to data portability and to lodge
            a complaint with a supervisory authority. [Placeholder: name the competent supervisory
            authority once the controller&rsquo;s registered address is finalized.]
          </p>
        </div>
      </Container>
    </section>
  );
}
