import type { Metadata } from "next";
import Container from "@/components/Container";
import Breadcrumbs from "@/components/Breadcrumbs";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: "Privacy policy for Canada EU Entry / OneTitel, describing how personal data is processed.",
  alternates: { canonical: "/privacy-policy" },
};

export default function PrivacyPolicyPage() {
  return (
    <section className="py-16 md:py-24">
      <Container className="max-w-2xl">
        <Breadcrumbs items={[{ href: "/", label: "Home" }, { href: "/privacy-policy", label: "Privacy Policy" }]} />
        <h1 className="mt-6 font-serif text-3xl font-semibold text-navy">Privacy Policy</h1>
        <p className="mt-2 text-sm font-medium uppercase tracking-wider text-accent">
          Draft — street address still to be confirmed; please have a qualified German/EU
          data-protection professional review before publication
        </p>

        <div className="prose-onetitel mt-8">
          <h2>1. Controller</h2>
          <p>
            Oliver Markus Müller, trading as &ldquo;Canada EU Entry&rdquo; / &ldquo;OneTitel&rdquo;,
            [Placeholder: full street address and postal code], Kirchweiler, Germany. Contact for
            data-protection matters: om@onetitel.de.
          </p>

          <h2>2. What data we process</h2>
          <ul>
            <li>Contact-form submissions (name, company, email, message content)</li>
            <li>Basic website analytics, where and if enabled with appropriate consent</li>
            <li>Technical log data generated by normal website operation</li>
          </ul>

          <h2>3. Purpose and legal basis</h2>
          <p>
            We process contact-form data to respond to your inquiry and, where relevant, to take
            steps prior to entering into a contract at your request (Art. 6(1)(b) GDPR), or based
            on our legitimate interest in handling business inquiries efficiently (Art. 6(1)(f)
            GDPR). Technical log data generated by normal website operation (e.g., for security
            and stability) is processed on the basis of our legitimate interest (Art. 6(1)(f)
            GDPR). [Placeholder: confirm final legal-basis wording with a qualified professional
            once the hosting/analytics setup is finalized.]
          </p>

          <h2>4. Cookies, tag management and consent</h2>
          <p>
            This website uses Google Tag Manager (GTM), a tag-management system provided by
            Google Ireland Limited, Gordon House, Barrow Street, Dublin 4, Ireland. GTM itself is
            a container technology that loads other tags/scripts (such as analytics or marketing
            pixels) and does not, by itself, set cookies or process personal data beyond
            technical information required to load those tags.
          </p>
          <p>
            [Placeholder: this site does not yet activate any analytics, advertising or
            marketing tags inside GTM. Before any such tag is enabled, a consent-management
            platform (cookie banner) must be implemented so that non-essential tags only fire
            after explicit, informed consent (Art. 6(1)(a) GDPR / Section 25 TTDSG), and this
            policy must be updated to name every specific tag added, its provider, purpose,
            data processed, retention period and opt-out mechanism.]
          </p>

          <h2>5. Data sharing</h2>
          <p>
            Personal data submitted via the contact form is only shared with service providers
            necessary to operate this website and respond to inquiries, such as our hosting
            provider (Vercel Inc.) and email service. [Placeholder: confirm and name the final
            hosting and email providers, and put data-processing agreements in place where
            required, before launch.]
          </p>

          <h2>6. International transfers</h2>
          <p>
            The controller is based in Germany and primarily serves Canadian companies. Where
            an inquiry or engagement involves transferring personal data to Canada or another
            country outside the EU/EEA, this is done based on the European Commission&rsquo;s
            adequacy decision for Canada (where applicable to the recipient) or, where no
            adequacy decision applies, on appropriate safeguards such as the EU Standard
            Contractual Clauses. Some service providers (e.g., hosting infrastructure) may
            process data on servers located outside the EU/EEA; in such cases, appropriate
            safeguards under Art. 44 et seq. GDPR are used. [Placeholder: confirm final provider
            list and applicable safeguards with a qualified professional.]
          </p>

          <h2>7. Retention</h2>
          <p>
            Contact-form and inquiry data is retained only for as long as necessary to process
            the inquiry and any resulting business relationship, and is deleted or anonymized
            once it is no longer needed, subject to any statutory retention obligations (e.g.,
            German commercial and tax law retention periods for business correspondence).
            [Placeholder: confirm exact retention periods with a qualified professional.]
          </p>

          <h2>8. Your rights</h2>
          <p>
            Under the GDPR, you have the right to access, rectify, erase, restrict or object to
            the processing of your personal data, and the right to data portability and to lodge
            a complaint with a supervisory authority. Based in Rhineland-Palatinate, the
            competent supervisory authority is expected to be the{" "}
            <em>
              Landesbeauftragte für den Datenschutz und die Informationsfreiheit
              Rheinland-Pfalz (LfDI RLP)
            </em>
            . [Placeholder: confirm the competent supervisory authority once the controller&rsquo;s
            registered address is finalized.]
          </p>
        </div>
      </Container>
    </section>
  );
}
